name: phuquoc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingises
  dartz: ^0.10.0
  # Remote API
  http: ^0.13.3
  shared_preferences: ^2.0.7
  #location
  location: ^4.3.0
  #image_convert
  image: ^3.0.8
  fluttertoast: ^8.0.8
  #dialog
  modal_bottom_sheet: ^2.0.0
  connectivity: ^3.0.6
  google_fonts: ^2.1.0
  flutter_svg: ^0.21.0
  #qr
  qr_flutter: ^4.0.0
  flutter_facebook_auth: ^3.5.6
  google_sign_in: ^5.1.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.10.0
  isoweek: ^1.1.3
  #chat
  chat_bubbles: ^1.1.0
  file_picker: ^4.2.7
  image_picker: ^0.8.4+1
  open_file: ^3.2.1
  uuid: ^3.0.5
  mime: ^1.0.1
  flutter_chat_types: ^3.1.4
  flutter_link_previewer: ^2.5.2
  intl: ^0.17.0
  meta: ^1.3.0
  photo_view: ^0.13.0
  diffutil_dart: ^3.0.0
  flutter_datetime_picker: ^1.5.1
  path_provider: ^2.0.4
  persistent_bottom_nav_bar: ^4.0.2
  web_socket_channel: ^2.1.0
  google_maps_flutter: ^2.0.9
  flutter_dotenv: ^5.0.2
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  dio: ^4.0.6
  freezed: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/illustration/
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/icons/app_function/
    - assets/bgs/
    - assets/hanhchinhvn/
    - assets/chat_icon/
    - assets/chat_icon/3.0x/
